### ISSUE TITLE
Phonegap Cloud Build Fails

### ISSUE THREAD

**Issue by Chinballs** [steveww/appdplugin#1]
I am attempting to use your plugin with a phonegap application but my build is failing. I compile using Adobe's cloud build for phonegap. I added this line to my config.xml file:

<gap:plugin name="com.appdynamics.appdplugin" version="4.0.3" />

I also submitted your plugin to the adobe phonegap cloud build server to be added as a plugin, which was accepted. You can view it here:

https://build.phonegap.com/plugins/3302

It appears in my plugin list like this:

Plugin	Source	Version	Latest	Platforms
com.appdynamics.appdplugin   	pgb	4.0.3	4.0.3	android,ios

So it is being picked up by adobe, and it is being included in the build. The build log results can be found here:

CompileC build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDynamicsAPI.o CreditApproval/Plugins/com.appdynamics.appdplugin/AppDynamicsAPI.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-generated-files.hmap -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-own-target-headers.hmap -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-all-target-headers.hmap -iquote /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/DerivedSources/armv7 -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/DerivedSources -F/project/build -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/CreditApproval-Prefix-hgqdflnnabcbmwdhyhgixaldcluj/CreditApproval-Prefix.pch -MMD -MT dependencies -MF /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDynamicsAPI.d --serialize-diagnostics /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDynamicsAPI.dia -c /project/CreditApproval/Plugins/com.appdynamics.appdplugin/AppDynamicsAPI.m -o /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDynamicsAPI.o
/project/CreditApproval/Plugins/com.appdynamics.appdplugin/AppDynamicsAPI.m:4:9: fatal error: 'ADEUMInstrumentation/ADEUMInstrumentation.h' file not found
#import <ADEUMInstrumentation/ADEUMInstrumentation.h>
        ^
1 error generated.

CompileC build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDCache.o CreditApproval/Plugins/com.appdynamics.appdplugin/AppDCache.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-generated-files.hmap -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-own-target-headers.hmap -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-all-target-headers.hmap -iquote /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/CreditApproval-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/DerivedSources/armv7 -I/project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/DerivedSources -F/project/build -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/6.1-6A1052d/Xcode/SharedPrecompiledHeaders/CreditApproval-Prefix-hgqdflnnabcbmwdhyhgixaldcluj/CreditApproval-Prefix.pch -MMD -MT dependencies -MF /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDCache.d --serialize-diagnostics /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDCache.dia -c /project/CreditApproval/Plugins/com.appdynamics.appdplugin/AppDCache.m -o /project/build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDCache.o

** BUILD FAILED **

The following build commands failed:
	CompileC build/CreditApproval.build/Release-iphoneos/CreditApproval.build/Objects-normal/armv7/AppDynamicsAPI.o CreditApproval/Plugins/com.appdynamics.appdplugin/AppDynamicsAPI.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Contact me for more details if you need them. Thanks!

**Comment by steveww** [comment]
Did you add the AppDynamics framework to your Xcode project?

**Comment by Chinballs** [comment]
With Phonegap build there is no Xcode involved on my end (I am developing on a Windows machine). I pass my phonegap code up to the build server and it reads the config file to choose which plugins are required. The android build also fails, but the windows phone one does not fail (since your plugin is android/ios only). Let me know if this isn't what you meant.

**Comment by steveww** [comment]
This plugin is designed to be used with the AppDynamics mobile SDK (available on both platforms iOS and Android). See https://docs.appdynamics.com/display/PRO40/Set+Up+and+Configure+Mobile+EUEM additionally have a good read of the PDF attached to this project. If you use the plugin as it was designed to be used you will find it works a treat, there are a number of production implementations in place.

**Comment by steveww** [comment]
Closed
