### ISSUE TITLE
Class Not Found error while fetching headers

### ISSUE THREAD

**Issue by rajendery** [steveww/appdplugin#5]
Here is my code to get the appd headers
var win = function (d) {
console.log("Success");
};
var fail = function (e) {
console.log("Error" +JSON.stringify(e));
}
var headerscb = function (d) {
console.log('got headers ' + d);
appdheaders = d;
}
cordova.exec(headerscb, fail, 'AppDynamics', 'getCorrelationHeaders', []);

And I am getting error saying "Class not found" .
Plugin installed : com.appdynamics.appdplugin 4.1.0

**Comment by steveww** [comment]
Sorry but I no longer work for AppDynamics and thus I will not be supporting this code anymore. Please contact AppDynamics support for assistance.

**Comment by rajendery** [comment]
Thanks for the response @steveww .
